### ISSUE TITLE
Ajouter des UTM au lien de création de compte

### ISSUE THREAD

**Issue by Thomaschauvin** [Intia/INFast-WooCommerce#16]
Sur la page https://wordpress.org/plugins/infast/#installation modifier le lien invitant à la création de compte https://intia.fr/fr/infast/ par  https://intia.fr/fr/infast/?utm_source=intia&utm_medium=woocommerce

Revoir également l'emoji 🔥 qui ne semble pas apparaître correctement.
![image](https://user-images.githubusercontent.com/36624644/218685888-a0aaabfd-3b82-4bee-afca-268bfa954037.png)

**Comment by Akta3d** [comment]
J'ai mis `utm_source=plugin_woocommerce` car j'avais déjà mis ces UTM via https://github.com/Intia/INFast-WooCommerce/issues/17
