### ISSUE TITLE
Ajouter des liens d'acquisition dans le plugin

### ISSUE THREAD

**Issue by Aleglise** [Intia/INFast-WooCommerce#17]
Nous voyons qu'il y a bcp plus de téléchargements que d'utilisation. 

L'embarquement est surement a améliorer et pour aider les prospects à embarquer et comprendre les frictions, il serait intéressant d'ajouter dans l'interface du plugin (dans un ecran de paramétrage ou un ecran Aide dédié) un lien "Obtenir de l'aide maintenant" (qui pointe vers https://intia.fr/?utm_source=plugin_woocommerce avec rédaction d'un message Intercom "Bonjour, J'ai besoin d'aide sur le plugin INFast pour Woocommerce" et un lien "Réserver un rendez-vous" https://calendly.com/intia-devis-factures/renseignement-plugin-woocomerce?utm_source=plugin_woocommerce

Exemple sur nu plugin que l'on utilise : 
![image](https://user-images.githubusercontent.com/8737709/218691003-438a748d-f349-40c1-89f8-33b5217694b5.png)

**Comment by Akta3d** [comment]
@Aleglise Pourras tu me préciser ce que tu veux.

Je ne comprends pas le lien ""Obtenir de l'aide maintenant" qui pointe juste vers le site intia.
Tu veux ensuite ajouter un message intercom sur cette url ?

**Comment by Aleglise** [comment]
L'experience de l'utilisateur est : je vais sur wordpress.org, je télécharge le plugin, je l'installe, je vais regarder le plugn dans mon admin wordpress. A aucun moment on embarque le user donc l'idée de cette issue est de mettre des liens pour amener l'utilisateurs sur intia.fr en declanchant  b un message intercom prerempli
