### ISSUE TITLE
Les frais de port non facturés

### ISSUE THREAD

**Issue by Thomaschauvin** [Intia/INFast-WooCommerce#20]
Suite au retour de [farah Camara](https://app.intercom.com/a/inbox/u897kg35/inbox/shared/unassigned/conversation/30964100309776?view=List), il semblerait que les frais de port paramétré sur Woocommerce ne soient pas pris en compte dans la facturation.

Farah Camara 63f29522239bf84edfa40c2c

**Comment by Akta3d** [comment]
Configuration des frais de port avec un prix fixe par poid
