### ISSUE TITLE
[Clients] TVA non appliquée

### ISSUE THREAD

**Issue by JordhanMadec** [Intia/INFast-WooCommerce#29]
Lorsqu'un client indique son numéro de TVA intracommunautaire, la facture générée reste sans TVA alors que le client à payé de la TVA. Il semblerait que cela arrive quand le numéro de TVA est invalide.

Voir cette discussion: https://app.intercom.com/a/inbox/u897kg35/inbox/shared/unassigned/conversation/30964100319667?view=List

**Comment by Akta3d** [comment]
En effet, la commande a été validée avec un numéro de TVA non valide.
Du coup la commande WooCommerce est générée avec TVA, mais la facture INFast avec de la TVA.

Le client a donc configuré le plugin sur les numéros de TVA obligeant d'insérer un numéro de TVA valide.
