### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Aleglise** [Intia/INFast-WooCommerce#40]
Descripcion

https://oci.wordpress.org/plugins/infast/#description

**Comment by Akta3d** [comment]
@Aleglise Je ne vois pas cette faute dans la description
Je ferme.
Réouvre si tu l'as retrouve et e veux bien plus d'info

**Comment by Akta3d** [comment]
Je viens de voir la typo.
Cela ne vient pas de chez nous mais du site wordpress.
https://oci.wordpress.org/plugins/infast/

Si tu vas sur https://wordpress.org/plugins/infast/ il n'y a pas de souci.

Très étrange.

**Comment by Aleglise** [comment]
C'ets peut etre une version en occitan ! 

¯\_(ツ)_/¯

Deal with it. Je laisse l'issue fermée
