### ISSUE TITLE
Articles non synchronisé et description article présente sur les factures

### ISSUE THREAD

**Issue by Thomaschauvin** [Intia/INFast-WooCommerce#42]
Suite retour sur le tchat de Guillaume Battaglini. Il semble y avoir des descriptions de produit qui apparaissent sur les factures.
Il y a également des articles non-synchronisés mais qui apparaissent bien sur les factures.

https://app.intercom.com/a/inbox/u897kg35/inbox/shared/all/conversation/30964100362274?view=List

**Comment by Akta3d** [comment]
Closed by https://github.com/Intia/INFast/issues/8635
